### ISSUE TITLE
ActionView::FileSystemResolver error while launching server on Rails 4.1.1.

### ISSUE THREAD

**Issue by raphaelpflieger** [tscolari/mobylette#44]
Firstly thanks a lot to all contributors behind this gem, I've already used it on a couple of projects and it always worked like a charm.

However since upgrading to Ruby 2.0.0. and Rails 4.1.1. I've not been able to use it, it makes the whole app crash while running 'rails server' (oh I'm on Windows 8.1, hope it's not related to that...)

Here are the logs:

```
C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/mobylette-08781e203eaa/lib/mobylette/resolvers/chained_fallback_resolver.rb:3:in `<module:Resolvers>': uninitialized constant ActionView::FileSystemResolver (NameError)
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/mobylette-08781e203eaa/lib/mobylette/resolvers/chained_fallback_resolver.rb:2:in `<module:Mobylette>'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/mobylette-08781e203eaa/lib/mobylette/resolvers/chained_fallback_resolver.rb:1:in `<top (required)>'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/mobylette-08781e203eaa/lib/mobylette.rb:5:in `require'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/mobylette-08781e203eaa/lib/mobylette.rb:5:in `<module:Mobylette>'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/mobylette-08781e203eaa/lib/mobylette.rb:3:in `<top (required)>'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
from C:/Users/Raphael/Dropbox/Sites/lacarteimmobiliere/config/application.rb:14:in `<top (required)>'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:79:in `require'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:79:in `block in server'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:76:in `tap'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:76:in `server'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'
```

It's referring to this line on application.rb:

```
Bundler.require(*Rails.groups)
```

Thank you for any help provided :)

**Comment by jacktang** [comment]
Hi, I added these two lines to the top of my application.rb to fix the issue

```
require "action_view"
require "action_view/template/resolver"
```
