### ISSUE TITLE
uninitialized constant ActionView::FileSystemResolver (NameError)

### ISSUE THREAD

**Issue by akeelahmedqureshi** [tscolari/mobylette#46]
Hi, 

I am facing following error when I run rails s command(I am using rails 4.1.5 and ruby 2.1.2)  

/home/cis/.rvm/gems/ruby-2.1.2@demo_cache/bundler/gems/mobylette-08781e203eaa/lib/mobylette/resolvers/chained_fallback_resolver.rb:3:in `<module:Resolvers>': uninitialized constant ActionView::FileSystemResolver (NameError)
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/bundler/gems/mobylette-08781e203eaa/lib/mobylette/resolvers/chained_fallback_resolver.rb:2:in`module:Mobylette'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/bundler/gems/mobylette-08781e203eaa/lib/mobylette/resolvers/chained_fallback_resolver.rb:1:in `<top (required)>'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/bundler/gems/mobylette-08781e203eaa/lib/mobylette.rb:5:in`module:Mobylette'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/bundler/gems/mobylette-08781e203eaa/lib/mobylette.rb:3:in `<top (required)>'
    from /home/cis/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:76:in`require'
    from /home/cis/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /home/cis/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:72:in`each'
    from /home/cis/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:72:in `block in require'
    from /home/cis/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:61:in`each'
    from /home/cis/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:61:in `require'
    from /home/cis/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.7.2/lib/bundler.rb:133:in`require'
    from /home/cis/demo_cache/config/application.rb:7:in `<top (required)>'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:79:in`require'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:79:in `block in server'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in`tap'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `server'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in`run_command!'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
    from /home/cis/demo_cache/bin/rails:8:in`require'
    from /home/cis/demo_cache/bin/rails:8:in `<top (required)>'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in`load'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in `call'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/spring-1.1.3/lib/spring/client/command.rb:7:in`call'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/spring-1.1.3/lib/spring/client.rb:26:in `run'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/spring-1.1.3/bin/spring:48:in`<top (required)>'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/spring-1.1.3/lib/spring/binstub.rb:11:in `load'
    from /home/cis/.rvm/gems/ruby-2.1.2@demo_cache/gems/spring-1.1.3/lib/spring/binstub.rb:11:in`<top (required)>'
    from /home/cis/demo_cache/bin/spring:16:in `require'
    from /home/cis/demo_cache/bin/spring:16:in`<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in`<main>'

**Comment by plombix** [comment]
same with rails 5.1.5 here
